### ISSUE TITLE
Efficiency of sparse matrix-vector multiplication and sparse version of basisstate

### ISSUE THREAD

**Issue by saulpila** [qojulia/QuantumOpticsBase.jl#11]
It seems that if `a=Ket(basis, v)` where `v` is a sparse vector, then the function `tensor(a,dagger(a))` generates a dense matrix. (Bacause `tensor(a::Ket, b::Bra)` calls `reshape` on  the kronecker product). Would it be possible to maintain the sparseness and return a sparse matrix if the vectors were originally sparse? When working with big sistem sizes, but with simple combinations of base states, those states can be efficiently represented using sparse vectors. If one needs to look at the density matrices (or projectors) of such states, generating a dense matrix is a waste of memory (and sometimes it is even unfeasible if the system is large enough) 

Changing this behavior in `tensor(a::Ket, b::Bra)` would automatically trickle down to `projector(a::Ket, b::Bra)`, `projector(a::Ket)`, `dm(x::Ket)` etc...

It would be also great if there was a sparse version of `basisstate(basis,index)` that generated a `Ket` with sparse `.data` field for this big system cases.

Thanks!

**Comment by david-pl** [comment]
The result of `tensor` is not a dense matrix: when reshaping the `kron` of two sparse vectors, the result is stored as `Base.ReshapedArray` which doesn't create a copy of the underlying data. This also happens when `tensor` is called with sparse `Ket` and `Bra` (the same goes for `dm` and `projector`). So the stored data is still sparse. If you were to return a sparse matrix, you would need to create a copy of the data, which you want to avoid for large systems.

I agree with the `basisstate` method though. An option for sparsity needs to be added.

**Comment by saulpila** [comment]
Hi, thank you for your response.

I was mistaken in saying that reshape makes the result sparse, I stand corrected. But it does make calculations very slow. 
Let me explain:
Say `d` is some big sparse vector with lots of zeros, and set `k=Ket(b,d)` for some basis `b`.
Calling 

**(a)** `projector(k)*k` 

is much much slower than calling the equivalent

**(b)** `Ket(b,kron(d,d')*d)`. 

(It is a silly example, but it is just to show my point).

The only difference is that there is a reshape in **(a)** and there is no reshape in **(b)**... 

The reshape makes the efficiency of the sparse matrix-vector operations go away (the slowdown occurs when the last product (`*k`) is performed). 

Do you think that this could be solved somehow? Say, by removing that reshape? It is really orders of magnitude slower: For `d` of length 100000 and 1 nonzero entry, then **(a)** takes 0.00085 seconds, and **(b)** takes almost two minutes.

**Comment by david-pl** [comment]
As you say, the `reshape` in `projector` can be removed. I will change it. The poor performance you're experiencing, though, is technically not an issue in QuantumOptics.jl. There is no specific method implemented for the product of a reshaped array with a sparse vector and so Julia uses the generic matrix-vector product fallback, meaning it's not taking advantage of the special sparse structure of `d`. This leads to poor performance.
As a quick workaround for now, you can just overwrite the `projector` function with `QuantumOpticsBase.projector(k::Ket) = Operator(k.basis, k.data*k.data')`.

More generally, we can avoid such problems by making the `Bra` type a lazy adjoint of `Ket`.

**Comment by saulpila** [comment]
Sounds great! Thank you so much.

**Comment by david-pl** [comment]
The upcoming release (v0.3) will have a proper sparse version of `basisstate` called `sparsebasisstate`. Note that you can also specify the number type used in the data now e.g. `sparsebasisstate(Float32, GenericBasis(5), 1)`. The `sparse` function is also overloaded for states so you can convert e.g. a `Ket` with dense `.data` by calling `sparse` on it. The `projector` function will return a sparse matrix when called with sparse states. Finally, for projectors on `SubspaceBasis` there is also a sparse version now called `sparseprojector`.
