### ISSUE TITLE
Method dense() doesn't preserve element type

### ISSUE THREAD

**Issue by sd109** [qojulia/QuantumOpticsBase.jl#17]
Is there a specific reason that calling dense(x::AbstractOperator) forces conversion to ComplexF64 data element type?

Maybe this is just left over from when all abstract operators were implemented as ComplexF64, or maybe I'm missing something, but to me it would make more sense to implement dense as

`dense(x::AbstractOperator) = Operator( x.basis_l, x.basis_r, Array(x.data) )`

since this would preserve the type of the data field. This would also be more consistent with the sparse method which does preserve data type.

**Comment by david-pl** [comment]
No it's an oversight and should be changed. Thanks for the report.
