### ISSUE TITLE
Fidelity

### ISSUE THREAD

**Issue by PhilipVinc** [qojulia/QuantumOpticsBase.jl#29]
Maybe I'm wrong, but shouldn't the fidelity be the square of that quantity?

https://en.wikipedia.org/wiki/Fidelity_of_quantum_states

https://github.com/qojulia/QuantumOpticsBase.jl/blob/de7abf7e7869ebd36cbdbd102c386553fda71799/src/metrics.jl#L189

**Comment by david-pl** [comment]
I think there are different conventions. The one that is implemented can be found e.g. in Nielsen & Chuang's Quantum Information and Quantum Computation (Eq. 9.53).
