### ISSUE TITLE
Type stability with `⊗`

### ISSUE THREAD

**Issue by ericphanson** [qojulia/QuantumOpticsBase.jl#8]
I think the definition of `⊗` in https://github.com/qojulia/QuantumOpticsBase.jl/blob/fbef602d8104dea1c85eec6de18f5db61a9a908d/src/bases.jl#L129

should be declared `const`, e.g.
```julia
const ⊗ = tensor
```
See for example the answers here: https://stackoverflow.com/q/48481547/12486544.

I came across this when writing this comment: https://github.com/JuliaLang/julia/pull/35150#issuecomment-600716217, which could be of interest to QuantumOptics as well.

**Comment by david-pl** [comment]
Thanks for pointing that out. I'll patch it.

**Comment by david-pl** [comment]
Fixed on master
