### ISSUE TITLE
Precompilation error

### ISSUE THREAD

**Issue by tnadolny** [qojulia/QuantumOpticsBase.jl#87]
Hi!
In version v0.3.10, precompilation results in `ERROR: LoadError: UndefVarError: @lazy_str not defined`. v0.3.9 works well for me, however.
I am not sure if this depends on other packages or parameters of my system.

**Comment by Krastanov** [comment]
Could you share the entire stack trace? `LazyString` and `@lazy_str` does not appear anywhere in the `QuantumOpticsBase` code, now or in 0.3.9, so this is probably a problem in a dependency or just an issue with something else in the environment.

**Comment by tnadolny** [comment]
Hi, thanks for your help! For me, it seems to be related to QuantumCumulants.jl.
However, it is most likely a problem on my part, and I will first clean up my Packages and try to install again from scratch.
Thanks again!

**Comment by amilsted** [comment]
We are using lazy strings in lazytensor at the moment using the string constructor `lazy"this is a lazy string with $variable interpolation"`.

**Comment by Krastanov** [comment]
the minimal supported version of julia is now 1.10, so this should not be a problem anymore
