### ISSUE TITLE
Ambiguity of `index` in `ptranspose(rho, index)`

### ISSUE THREAD

**Issue by zejian-li** [qojulia/QuantumOpticsBase.jl#97]
From the docstring "Partial transpose of rho with respect to subspace specified by index" one might expect the function to perform the partial transpose on the subsystem specified by the index, i.e. if $\hat{\rho} = \hat{A}\otimes\hat{B}$,    
ptranspose($\hat{\rho}$,1) = $\hat{A}^T\otimes \hat{B}$    
instead of    
ptranspose($\hat{\rho}$,1) = $\hat{A}\otimes \hat{B}^T$, which is what the function actually does.

**Comment by david-pl** [comment]
@zejian-li that's a bug. It should actually be the other way around. I never noticed as I only used the `ptranspose` together with the `negativity` where the order of the subsystems doesn't matter. That needs to be fixed and we need some tests for `ptranspose` only. 

Feel free to submit a PR with your changes. Although we'll need to fix the order of the single index version first.
